services:

  db:
    image: mariadb:10.6.4-focal
    container_name: mysql
    volumes:
      - /www/mysql:/var/lib/mysql
      - ./stars.sql:/docker-entrypoint-initdb.d/stars.sql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8082:3306"

  php:
    build:
      context: .
      dockerfile: ./Dockerfile.php-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html
    restart: always
    

  app:
    image: nginx:latest
    container_name: stars
    volumes:
      - ./html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - db
      - php
    ports:
      - "8080:80"


